tattoo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from tattoo_heritage import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('heritage/', include('tattoo_heritage.urls')),
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tattoo_heritage/urls.py
from django.urls import path
from . import views

app_name = 'heritage'

urlpatterns = [
    path('artists/', views.disp_artist, name='disp_artist'),
    path('addartist/', views.add_artist, name='add_artist'),
    path('', views.user_login, name='user_login'),
    path('viewwork/', views.view_work, name='view_work'),
    path('gal1', views.add_gal1, name='gal1'),
    path('addwork', views.add_work, name='addwork'),
    path('delgal', views.del_gal, name='del_gal'),
    path('delwork', views.del_work, name='del_wrk'),
    path('updateartist', views.update_artist, name='update_artist'),

]

tattoo_heritage/models.py
from django.db import models
import uuid

# Create your models here.

class Artist(models.Model):
    a_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    a_name = models.CharField(max_length=120)
    a_img = models.ImageField(upload_to='artists', blank=True)
    a_contact = models.CharField(max_length=100, blank=True)
    a_email = models.EmailField(blank=True)
    a_des = models.CharField(max_length=1000, default="This is tattoo artist.")
    a_fb = models.URLField(blank=True)
    a_insta =models.URLField(blank=True)

    def __str__(self):
        return self.a_name

class artist_work(models.Model):
    w_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    a_id = models.ForeignKey(Artist, on_delete=models.CASCADE)
    w_img = models.ImageField(upload_to='work', blank=False)

    def __str__(self):
        return self.a_id.a_name

class gallery1(models.Model):
    g1_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    g1_img = models.ImageField(upload_to='gallery1', blank=True)

    def __str__(self):
        return str(self.g1_img)

tattoo_heritage/forms.py
from django import forms
from .models import Artist, gallery1,artist_work

class AddArtist_Form(forms.ModelForm):

    class Meta:
        model = Artist
        fields = ['a_name', 'a_img', 'a_contact', 'a_email', 'a_des', 'a_fb', 'a_insta']

class Addimggal1_Form(forms.ModelForm):

    class Meta:
        model = gallery1
        fields = ['g1_img']


class AddWork_form(forms.ModelForm):
    class Meta:
        model = artist_work
        fields = ['a_id', 'w_img']

tattoo_heritage/views.py
from django.shortcuts import render

from tattoo import settings
from .models import Artist
from .forms import *
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect,HttpRequest
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from tattoo_heritage.models import Artist


# Create your views here.
def index(request):
    index_page = loader.get_template("index.html")
    context = {}
    result1 = gallery1.objects.all()
    res_artist = Artist.objects.all()
    context["gal1_img"] = result1
    context["art"] = res_artist
    if request.method == 'POST':
        name = str(request.POST.get('uname'))
        semail = str(request.POST.get('uemail'))
        msg = request.POST.get('umsg')
        ph = request.POST.get('uph')
        send_mail(semail, msg, settings.EMAIL_HOST_USER,
                  ['collegeworks2019@gmail.com'], fail_silently=False)
        context["success_msg"] = "Sucessfully send"
        return HttpResponse(index_page.render(context, request))
    return HttpResponse(index_page.render(context, request))


def view_work(request):
    if request.method == 'POST':
        art_id = request.POST.get('ar_id')
        art_work = artist_work.objects.filter(a_id=art_id)
        return render(request, 'View_Work.html', {'artist_work': art_work})
    return render(request, 'View_Work.html')


@login_required
def disp_artist(request):
    result_disp = Artist.objects.order_by("a_name")
    if request.method == 'POST':
        i_a_id = request.POST.get('picid')
        Artist.objects.filter(a_id=i_a_id).delete()
    return render(request, 'disp_artist.html', {'artist': result_disp})


@login_required
def add_artist(request):
    if request.method == 'POST':
        form = AddArtist_Form(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'addArtist.html', {'sucess_msg': 'Sucessfully added', 'form': form})
    else:
        form = AddArtist_Form
        return render(request, 'addArtist.html', {'form': form})


@login_required
def add_gal1(request):
    if request.method == 'POST':
        form1 = Addimggal1_Form(request.POST, request.FILES)
        if form1.is_valid():
            form1.save()
            return render(request, "gal1.html", {'sucess_msg': 'Sucessfully added', 'form': form1})
        else:
            form1 = Addimggal1_Form
            return render(request, 'gal1.html', {'fail_msg': 'Failed to add', 'form': form1})
    else:
        form1 = Addimggal1_Form
        return render(request, 'gal1.html', {'form': form1})

@login_required
def add_work(request):
    if request.method == 'POST':
        form5 = AddWork_form(request.POST, request.FILES)
        if form5.is_valid():
            form5.save()
            return render(request, 'addWork.html', {'sucess_msg': 'Sucessfully added', 'form': form5})
    else:
        form5 = AddWork_form
        return render(request, 'addWork.html', {'form': form5})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return render(request, 'disp_artist.html')
        else:
            fail = {'wrong': 'Invalid Username or Password'}
            return render(request, 'login.html', context=fail)
    return render(request, 'login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def del_gal(request):
    res_disp = gallery1.objects.all()
    if request.method == 'POST':
        img_id = request.POST.get('img_id')
        gallery1.objects.filter(g1_id=img_id).delete()
        return render(request, 'disp_gal.html', {'gal': res_disp})
    return render(request, 'disp_gal.html',{'gal': res_disp})


@login_required
def del_work(request):
    res_disp = artist_work.objects.all()
    if request.method == 'POST':
        im_id = request.POST.get('im_id')
        artist_work.objects.filter(w_id = im_id).delete()
        return render(request, 'disp_work.html', {'work':res_disp})
    return render(request, 'disp_work.html', {'work': res_disp})

@login_required
def update_artist(request):
    if request.method == 'POST':
        a_id = request.POST.get('id')
        a_name = request.POST.get('name')
        a_img = request.FILES.get('imgf')
        a_contact = request.POST.get('contact')
        a_email = request.POST.get('email')
        a_des = request.POST.get('des')
        a_fb = request.POST.get('fb')
        a_insta = request.POST.get('insta')
        a = Artist.objects.get(a_id = a_id)
        a.a_name = a_name
        a.a_img = a_img
        a.a_contact = a_contact
        a.a_email = a_email
        a.a_des = a_des
        a.a_fb = a_fb
        a.a_insta = a_insta
        a.save()
        # Artist.objects.filter(a_id=a_id).update(a_name= a_name, a_img= a_img, a_contact=a_contact, a_email=a_email,
        #                 a_des=a_des, a_fb=a_fb, a_insta=a_insta)

        return render(request, 'disp_artist.html')
    return render(request, 'disp_artist.html')

templates/View_Work.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>This is view work</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style>
        .mySlides {
            display: none;
        }
    </style>
</head>
<body style="background-color:black;">

    <div class="w3-content w3-display-container">
        {% for n in artist_work %}
        <img class="mySlides" src="{{ MEDIA_URL }}{{ n.w_img.url }}" width="100%" height="auto">
        {% endfor %}
        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
    </div>


<script>
    var slideIndex = 1;
    showDivs(slideIndex);

    function plusDivs(n) {
        showDivs(slideIndex += n);
    }

    function showDivs(n) {
        var i;
        var x = document.getElementsByClassName("mySlides");
        if (n > x.length) {
            slideIndex = 1
        }
        if (n < 1) {
            slideIndex = x.length
        }
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        x[slideIndex - 1].style.display = "block";
    }
</script>


</body>
</html>

templates/addArtist.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Artist</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">

</form>
{% if sucess_msg %}
    <h1>{{ sucess_msg }}</h1>
{% endif %}

</body>
</html>
{% endblock %}

templates/addWork.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Work</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">

</form>
{% if sucess_msg %}
    <h1>{{ sucess_msg }}</h1>
{% endif %}

</body>
</html>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
     <link rel="stylesheet" href={% static "css/welcome.css" %} type='text/css'>
</head>
<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'heritage:disp_artist' %}">View Artists</a></li>
                <li><a href="{% url 'heritage:add_artist' %}">Add Artist</a></li>
                <li><a href="{% url 'heritage:del_gal' %}">View Gallery</a></li>
                <li><a href="{% url 'heritage:gal1' %}">Add Gallery</a></li>
                <li><a href="{% url 'heritage:del_wrk' %}">View Work</a></li>
                <li><a href="{% url 'heritage:addwork' %}">Add Work</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li>Login</li>
            {% endif %}
        </ul>
        <div class="container">
            {% block body_block %}
{#            Anything inside this will be inheriated if extended#}
            {% endblock %}
        </div>
    </nav>
</body>
</html>

templates/disp_artist.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
    <h1>This is display artist page</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Description</th>
            <th>FB link</th>
            <th>Insta link</th>
            <th>Image</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for a in artist %}
            <tr>
                <form method="post" action="{% url 'heritage:update_artist' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <td><input type="text" value="{{ a.a_name }}" name="name"></td>
                    <td><input type="text" value="{{ a.a_contact }}" name="contact"></td>
                    <td><input type="email" value="{{ a.a_email }}" name="email"></td>
                    <td><input type="text" value="{{ a.a_des }}" name="des"></td>
                    <td><input type="text" value="{{ a.a_fb }}" name="fb"></td>
                    <td><input type="text" value="{{ a.a_insta }}" name="insta"></td>
                    <td><input type="file" name="imgf"></td>
                    <td><input type="submit" value="edit"></td>
                    <input type="hidden" value="{{ a.a_id }}" name="id">
                </form>
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" value="{{ a.a_id }}" name="picid">
                        <input type="submit" value="delete">
                    </form>
                </td>
            </tr>
        {% endfor %}
    </table>
    </body>
    </html>
{% endblock %}

templates/disp_gal.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View and Delete from Gallery</title>
</head>
<body>
{% for n in gal %}
    <img src="{{ MEDIA_URL }}{{n.g1_img.url}}" alt="no preiver" width="50%" height="50%" alt="">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" value="{{ n.g1_id }}" name="img_id">
        <input type="submit" value="delete">
    </form>
{% endfor %}

</body>
</html>
{% endblock %}

templates/disp_work.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Display_work</title>
        {% for n in work %}
            <h3>Artist: {{ n.a_id.a_name }}</h3>
            <img src={{ MEDIA_URL }}{{ n.w_img.url }} alt="No_Preview" width="40%" height="40%">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="{{ n.w_id }}" name="im_id">
                <input type="submit" value="Delete">
            </form>
        {% endfor %}
    </head>
    <body>

    </body>
    </html>
{% endblock %}

templates/gal1.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Gallery</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">

</form>
{% if sucess_msg %}
    <h1>{{ sucess_msg }}</h1>
{% else %}
    <h1>{{ fail_msg }}</h1>
{% endif %}

</body>
</html>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block body_block %}
    <h1>Please Login</h1>
    {% if wrong %}
        <h1>{{ wrong }}</h1>
    {% endif %}
    <form action="{% url 'heritage:user_login' %}" method="POST">
    {% csrf_token %}
        <label>Username</label>
        <input type="text" name = "username" placeholder="Enter username">

        <label>Passwords:</label>
        <input type="password" name = "password">

        <input type="submit" value="Submit">
    </form>
{% endblock %}